from __future__ import annotations

from signalforge.models import InterfaceSchema


def generate_markdown(schema: InterfaceSchema) -> str:
    lines = [
        "# SignalForge Interface Documentation",
        "",
        "_Generated by SignalForge from the provided schema._",
        "",
        "## Component Summary",
        "",
        "| Component | Message Count |",
        "| --- | ---: |",
    ]

    for component in schema.components:
        lines.append(f"| {component.name} | {len(component.messages)} |")

    lines.extend(["", "## Messages", ""])

    for component in schema.components:
        lines.append(f"### {component.name}")
        lines.append("")
        lines.append("| Message | ID | Direction | Frequency (Hz) | Field Count |")
        lines.append("| --- | ---: | --- | ---: | ---: |")
        for message in component.messages:
            frequency = f"{float(message.frequency_hz):g}" if message.frequency_hz is not None else "-"
            lines.append(
                f"| {message.name} | {message.id} | {message.direction} | {frequency} | {len(message.fields)} |"
            )
        lines.append("")
        for message in component.messages:
            lines.append(f"#### {message.name}")
            lines.append("")
            lines.append(f"- Direction: `{message.direction}`")
            lines.append(f"- Message ID: `{message.id}`")
            if message.frequency_hz is not None:
                lines.append(f"- Frequency: `{float(message.frequency_hz):g} Hz`")
            lines.append("")
            lines.append("| Field | Type | Unit |")
            lines.append("| --- | --- | --- |")
            for field in message.fields:
                lines.append(f"| {field.name} | {field.type} | {field.unit or '-'} |")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"
