from __future__ import annotations

from signalforge.models import InterfaceSchema


PYTHON_TYPE_MAP = {
    "uint8": "int",
    "uint16": "int",
    "uint32": "int",
    "int32": "int",
    "float32": "float",
    "float64": "float",
    "bool": "bool",
    "string": "str",
}


def generate_python(schema: InterfaceSchema) -> str:
    unique_messages = _collect_unique_messages(schema)
    lines = [
        '"""Generated by SignalForge. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
    ]

    for component_name, message_names in _component_usage(schema).items():
        lines.append(f"# Component: {component_name}")
        lines.append(f"{component_name}_messages = {message_names!r}")
        lines.append("")

    for message in unique_messages:
        lines.append("@dataclass(slots=True)")
        lines.append(f"class {message.name}:")
        for field in message.fields:
            lines.append(f"    {field.name}: {PYTHON_TYPE_MAP[field.type]}")
        if not message.fields:
            lines.append("    pass")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _collect_unique_messages(schema: InterfaceSchema):
    seen: dict[str, object] = {}
    for component in schema.components:
        for message in component.messages:
            seen.setdefault(message.name, message)
    return list(seen.values())


def _component_usage(schema: InterfaceSchema) -> dict[str, list[str]]:
    return {
        component.name: [message.name for message in component.messages]
        for component in schema.components
    }
