from __future__ import annotations

from signalforge.models import InterfaceSchema


RUST_TYPE_MAP = {
    "uint8": "u8",
    "uint16": "u16",
    "uint32": "u32",
    "int32": "i32",
    "float32": "f32",
    "float64": "f64",
    "bool": "bool",
    "string": "String",
}


def generate_rust(schema: InterfaceSchema) -> str:
    unique_messages = _collect_unique_messages(schema)
    lines = [
        "// Generated by SignalForge. Do not edit by hand.",
        "",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub enum MessageDirection {",
        "    Publish,",
        "    Subscribe,",
        "    Request,",
        "    Response,",
        "}",
        "",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub enum MessageKind {",
    ]

    for message in unique_messages:
        lines.append(f"    {message.name},")
    lines.extend(["}", ""])

    for message in unique_messages:
        lines.append("#[derive(Debug, Clone, PartialEq)]")
        lines.append(f"pub struct {message.name} {{")
        for field in message.fields:
            lines.append(f"    pub {field.name}: {RUST_TYPE_MAP[field.type]},")
        lines.append("}")
        lines.append("")
        lines.append(f"impl Default for {message.name} {{")
        lines.append("    fn default() -> Self {")
        lines.append("        Self {")
        for field in message.fields:
            lines.append(f"            {field.name}: {default_rust_value(field.type)},")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def default_rust_value(field_type: str) -> str:
    if field_type == "string":
        return "String::new()"
    if field_type == "bool":
        return "false"
    if field_type.startswith("float"):
        return "0.0"
    return "0"


def _collect_unique_messages(schema: InterfaceSchema):
    seen: dict[str, object] = {}
    for component in schema.components:
        for message in component.messages:
            seen.setdefault(message.name, message)
    return list(seen.values())
